/**
 * Portal specifications for image resizing (photo + signature).
 * -----------------------------------------------------------
 * Standard rules for Indian government & global portal forms.
 *
 * SPEC ACCURACY IS THE PRODUCT. A wrong dimension/KB cap means a rejected
 * application — so every spec carries provenance: the official `source`, a
 * `verification` status, and the date it was last confirmed (`verifiedOn`).
 * Use lib/specRegistry.ts to surface this on pages and to flag stale specs.
 */

/** Where a spec's numbers came from. */
export interface SpecSource {
  /** Official portal / notification URL the numbers were taken from. */
  url: string;
  /** Short human label, e.g. "SSC official portal". */
  label: string;
}

/**
 * "official"     = numbers confirmed against `source` on `verifiedOn`.
 * "needs-review" = carried from earlier code; not yet re-confirmed live.
 */
export type VerificationStatus = "official" | "needs-review";

export interface PortalSpec {
  id: string;
  name: string;
  photoLimitKb: number;
  photoMinKb?: number;
  sigLimitKb?: number;
  sigMinKb?: number;
  photoWidthPx?: number;
  photoHeightPx?: number;
  sigWidthPx?: number;
  sigHeightPx?: number;
  photoAspectRatio?: number; // width / height
  sigAspectRatio?: number;
  description: string;
  /** Provenance (optional for back-compat; should be set for all live specs). */
  source?: SpecSource;
  verification?: VerificationStatus;
  /** ISO date (YYYY-MM-DD) the numbers were last confirmed against `source`. */
  verifiedOn?: string;
}

export const PORTAL_PRESETS: Record<string, PortalSpec> = {
  ssc: {
    id: "ssc",
    name: "SSC (Staff Selection Commission)",
    photoLimitKb: 50,
    photoMinKb: 20,
    sigLimitKb: 20,
    sigMinKb: 10,
    photoWidthPx: 350,
    photoHeightPx: 450,
    sigWidthPx: 140,
    sigHeightPx: 60,
    photoAspectRatio: 3.5 / 4.5,
    sigAspectRatio: 4 / 2,
    description: "Staff Selection Commission photo (20-50 KB, 3.5x4.5cm) and signature (10-20 KB, 4.0x2.0cm).",
    source: { url: "https://ssc.gov.in", label: "SSC official portal (ssc.gov.in)" },
    verification: "official",
    verifiedOn: "2026-06-08",
  },
  upsc: {
    id: "upsc",
    name: "UPSC (Union Public Service Commission)",
    photoLimitKb: 300,
    photoMinKb: 20,
    sigLimitKb: 100,
    sigMinKb: 20,
    photoWidthPx: 350,
    photoHeightPx: 350, // UPSC wants square aspects
    sigWidthPx: 350,
    sigHeightPx: 350,
    photoAspectRatio: 1,
    sigAspectRatio: 1,
    description: "Union Public Service Commission online application. Photo 20-300 KB; signature 20-100 KB (three stacked signatures), ~350x350 px.",
    source: { url: "https://upsconline.nic.in", label: "UPSC online application (upsconline.nic.in)" },
    verification: "needs-review",
  },
  ds160: {
    id: "ds160",
    name: "US DS-160 (Visa)",
    photoLimitKb: 240,
    photoWidthPx: 600,
    photoHeightPx: 600,
    photoAspectRatio: 1,
    description: "Online US Visa Application DS-160. Square photo (600x600px up to 1200x1200px), under 240 KB limit, white background.",
    source: { url: "https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/photos.html", label: "US Dept. of State photo requirements" },
    verification: "official",
    verifiedOn: "2026-06-08",
  },
  "passport-seva": {
    id: "passport-seva",
    name: "Passport Seva (India)",
    photoLimitKb: 250,
    photoMinKb: 10,
    sigLimitKb: 100,
    sigMinKb: 10,
    photoWidthPx: 630,
    photoHeightPx: 810,
    sigWidthPx: 450,
    sigHeightPx: 150,
    photoAspectRatio: 3.5 / 4.5,
    sigAspectRatio: 4.5 / 1.5,
    description: "Passport Seva online portal. Photo 630x810 px, 10-250 KB, white background, face 80-85%. Signature rectangular, up to 100 KB.",
    source: { url: "https://www.passportindia.gov.in", label: "Passport Seva (passportindia.gov.in)" },
    verification: "official",
    verifiedOn: "2026-06-08",
  },
  oci: {
    id: "oci",
    name: "OCI Card (India)",
    photoLimitKb: 200,
    sigLimitKb: 200,
    photoWidthPx: 360,
    photoHeightPx: 360,
    sigWidthPx: 600,
    sigHeightPx: 200,
    photoAspectRatio: 1,
    sigAspectRatio: 3,
    description: "OCI registration. Square photo 200-900 px, up to 200 KB. Signature 3:1 rectangular (e.g. 600x200 px), up to 200 KB.",
    source: { url: "https://ociservices.gov.in", label: "OCI Services (ociservices.gov.in)" },
    verification: "official",
    verifiedOn: "2026-06-08",
  },
  rrb: {
    id: "rrb",
    name: "Railway Recruitment Board (RRB)",
    photoLimitKb: 100,
    photoMinKb: 20,
    sigLimitKb: 40,
    sigMinKb: 10,
    photoWidthPx: 350,
    photoHeightPx: 450,
    sigWidthPx: 140,
    sigHeightPx: 60,
    photoAspectRatio: 3.5 / 4.5,
    sigAspectRatio: 14 / 6,
    description: "Railway Recruitment Board (rrbapply.gov.in). Photo ~20-100 KB, signature ~10-40 KB. Limits vary by sub-exam (NTPC/Group D/ALP) — confirm the current notification. NOTE: These specs are unverified — always check the official RRB notification before submitting.",
    source: { url: "https://rrbapply.gov.in", label: "RRB Application Portal (rrbapply.gov.in)" },
    verification: "needs-review",
  },
  ibps: {
    id: "ibps",
    name: "IBPS Exams",
    photoLimitKb: 50,
    photoMinKb: 20,
    sigLimitKb: 20,
    sigMinKb: 10,
    photoWidthPx: 200,
    photoHeightPx: 230,
    sigWidthPx: 140,
    sigHeightPx: 60,
    photoAspectRatio: 20 / 23,
    sigAspectRatio: 14 / 6,
    description: "Institute of Banking Personnel Selection photo (20-50 KB, 200x230px) and signature (10-20 KB, 140x60px, black ink).",
    source: { url: "https://ibps.in", label: "IBPS official portal (ibps.in)" },
    verification: "official",
    verifiedOn: "2026-06-08",
  },
  sbi: {
    id: "sbi",
    name: "SBI PO / Careers",
    photoLimitKb: 50,
    photoMinKb: 20,
    sigLimitKb: 20,
    sigMinKb: 10,
    photoWidthPx: 200,
    photoHeightPx: 230,
    sigWidthPx: 140,
    sigHeightPx: 60,
    photoAspectRatio: 20 / 23,
    sigAspectRatio: 14 / 6,
    description: "State Bank of India PO recruitment photo (20-50 KB, 200x230px) and signature (10-20 KB, 140x60px, black ink).",
    source: { url: "https://sbi.co.in/web/careers", label: "SBI Careers (sbi.co.in/web/careers)" },
    verification: "official",
    verifiedOn: "2026-06-08",
  },
  nta: {
    id: "nta",
    name: "NTA (NEET / JEE)",
    photoLimitKb: 200,
    photoMinKb: 10,
    sigLimitKb: 100,
    sigMinKb: 10,
    photoWidthPx: 350,
    photoHeightPx: 450,
    sigWidthPx: 280,
    sigHeightPx: 120,
    photoAspectRatio: 3.5 / 4.5,
    sigAspectRatio: 3.5 / 1.5,
    description: "NTA exams (NEET, JEE Main). Passport photo 3.5x4.5cm, 10-200 KB; signature 3.5x1.5cm, 10-100 KB, JPG. (NEET also needs a separate 4x6 inch postcard photo.)",
    source: { url: "https://exams.nta.ac.in", label: "NTA exams portal (nta.ac.in)" },
    verification: "official",
    verifiedOn: "2026-06-08",
  },
  rbi: {
    id: "rbi",
    name: "RBI (Grade B / Assistant)",
    photoLimitKb: 50,
    photoMinKb: 20,
    sigLimitKb: 20,
    sigMinKb: 10,
    photoWidthPx: 200,
    photoHeightPx: 230,
    sigWidthPx: 140,
    sigHeightPx: 60,
    photoAspectRatio: 20 / 23,
    sigAspectRatio: 14 / 6,
    description: "Reserve Bank of India recruitment (Grade B, Assistant). Photo 20-50 KB, 200x230 px; signature 10-20 KB, 140x60 px, black ink, JPG.",
    source: { url: "https://opportunities.rbi.org.in", label: "RBI Opportunities (rbi.org.in)" },
    verification: "official",
    verifiedOn: "2026-06-08",
  },
  ctet: {
    id: "ctet",
    name: "CTET (CBSE)",
    photoLimitKb: 100,
    photoMinKb: 10,
    sigLimitKb: 30,
    sigMinKb: 3,
    photoWidthPx: 350,
    photoHeightPx: 450,
    sigWidthPx: 280,
    sigHeightPx: 120,
    photoAspectRatio: 3.5 / 4.5,
    sigAspectRatio: 3.5 / 1.5,
    description: "CBSE CTET. Photo 3.5x4.5cm, 10-100 KB; signature 3.5x1.5cm, 3-30 KB, JPG. The portal auto-rejects wrong dimensions, so match exactly.",
    source: { url: "https://ctet.nic.in", label: "CTET (ctet.nic.in)" },
    verification: "official",
    verifiedOn: "2026-06-08",
  },
  uppsc: {
    id: "uppsc",
    name: "UPPSC (Uttar Pradesh PSC)",
    photoLimitKb: 50,
    photoMinKb: 20,
    sigLimitKb: 30,
    sigMinKb: 10,
    photoWidthPx: 180,
    photoHeightPx: 216,
    sigWidthPx: 216,
    sigHeightPx: 108,
    photoAspectRatio: 180 / 216,
    sigAspectRatio: 216 / 108,
    description: "Uttar Pradesh PSC. Photo ~20-50 KB (180x216 px), signature ~10-30 KB (216x108 px), JPG, scanned at 200 DPI. Specs vary by notification — confirm the current one.",
    source: { url: "https://uppsc.up.nic.in", label: "UPPSC (uppsc.up.nic.in)" },
    verification: "needs-review",
  },
  bpsc: {
    id: "bpsc",
    name: "BPSC (Bihar PSC)",
    photoLimitKb: 50,
    photoMinKb: 20,
    sigLimitKb: 20,
    sigMinKb: 10,
    photoWidthPx: 200,
    photoHeightPx: 230,
    sigWidthPx: 220,
    sigHeightPx: 100,
    photoAspectRatio: 20 / 23,
    sigAspectRatio: 220 / 100,
    description: "Bihar PSC. Photo ~20-50 KB (200x230 px), signature ~10-20 KB (220x100 px), JPG. Specs vary by notification — confirm the current one.",
    source: { url: "https://bpsc.bihar.gov.in", label: "BPSC (bpsc.bihar.gov.in)" },
    verification: "needs-review",
  },
  mpsc: {
    id: "mpsc",
    name: "MPSC (Maharashtra PSC)",
    photoLimitKb: 50,
    photoMinKb: 20,
    sigLimitKb: 20,
    sigMinKb: 10,
    photoWidthPx: 200,
    photoHeightPx: 230,
    sigWidthPx: 140,
    sigHeightPx: 60,
    photoAspectRatio: 20 / 23,
    sigAspectRatio: 14 / 6,
    description: "Maharashtra PSC. Photo ~20-50 KB (200x230 px), signature ~10-20 KB (140x60 px), JPG. Specs vary by notification — confirm the current one.",
    source: { url: "https://mpsc.gov.in", label: "MPSC (mpsc.gov.in)" },
    verification: "needs-review",
  },

  // ---------------------------------------------------------------------------
  // National exams (NTA / GATE) — confirmed against official bulletins, 2026-06.
  // ---------------------------------------------------------------------------
  gate: {
    id: "gate",
    name: "GATE (Engineering)",
    photoLimitKb: 600,
    photoMinKb: 5,
    sigLimitKb: 300,
    sigMinKb: 3,
    photoWidthPx: 350,
    photoHeightPx: 450,
    sigWidthPx: 400,
    sigHeightPx: 130,
    photoAspectRatio: 3.5 / 4.5,
    sigAspectRatio: 400 / 130,
    description: "Graduate Aptitude Test in Engineering. Photo 5-600 KB (200x260 to 530x690 px, 3.5x4.5 cm); signature 3-300 KB (250x80 to 580x180 px), JPEG. The KB cap is set by the conducting IIT each year (600 KB for GATE 2026 / IIT Guwahati) — confirm the current bulletin.",
    source: { url: "https://gate2026.iitg.ac.in", label: "GATE 2026 (IIT Guwahati)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  "ugc-net": {
    id: "ugc-net",
    name: "UGC-NET (NTA)",
    photoLimitKb: 200,
    photoMinKb: 10,
    sigLimitKb: 50,
    sigMinKb: 10,
    description: "UGC National Eligibility Test (conducted by NTA). Photo 10-200 KB; signature 10-50 KB; JPG/JPEG only. NTA specifies file size and format but no fixed pixel dimensions.",
    source: { url: "https://ugcnet.nta.ac.in", label: "NTA UGC-NET (ugcnet.nta.ac.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  "csir-net": {
    id: "csir-net",
    name: "CSIR-NET (NTA)",
    photoLimitKb: 200,
    photoMinKb: 10,
    sigLimitKb: 50,
    sigMinKb: 10,
    description: "Joint CSIR-UGC NET (conducted by NTA). Photo 10-200 KB; signature 10-50 KB; JPG/JPEG only. NTA specifies file size and format but no fixed pixel dimensions.",
    source: { url: "https://csirnet.nta.ac.in", label: "NTA CSIR-NET (csirnet.nta.ac.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },

  // ---------------------------------------------------------------------------
  // Defence (UPSC OTR portal + IAF) — confirmed against official upload PDFs.
  // ---------------------------------------------------------------------------
  nda: {
    id: "nda",
    name: "NDA (National Defence Academy)",
    photoLimitKb: 100,
    photoMinKb: 50,
    sigLimitKb: 50,
    sigMinKb: 10,
    photoWidthPx: 350,
    photoHeightPx: 450,
    sigWidthPx: 420,
    sigHeightPx: 120,
    photoAspectRatio: 3.5 / 4.5,
    sigAspectRatio: 420 / 120,
    description: "National Defence Academy (conducted by UPSC via upsconline.nic.in). Photo 50-100 KB (3.5x4.5 cm, 240x320 to 480x640 px); signature 10-50 KB (7x2 cm box, 280x80 to 560x160 px); JPG/JPEG.",
    source: { url: "https://upsconline.nic.in", label: "UPSC online (upsconline.nic.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  cds: {
    id: "cds",
    name: "CDS (Combined Defence Services)",
    photoLimitKb: 100,
    photoMinKb: 50,
    sigLimitKb: 50,
    sigMinKb: 10,
    photoWidthPx: 350,
    photoHeightPx: 450,
    sigWidthPx: 420,
    sigHeightPx: 120,
    photoAspectRatio: 3.5 / 4.5,
    sigAspectRatio: 420 / 120,
    description: "Combined Defence Services (conducted by UPSC via upsconline.nic.in). Photo 50-100 KB (3.5x4.5 cm, 240x320 to 480x640 px); signature 10-50 KB (7x2 cm box, 280x80 to 560x160 px); JPG/JPEG.",
    source: { url: "https://upsconline.nic.in", label: "UPSC online (upsconline.nic.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  afcat: {
    id: "afcat",
    name: "AFCAT (Air Force)",
    photoLimitKb: 200,
    photoMinKb: 100,
    sigLimitKb: 150,
    sigMinKb: 80,
    description: "Air Force Common Admission Test. Photo 100-200 KB; signature 80-150 KB; thumb impression 50-100 KB; JPG/JPEG. The 2026 notification specifies file size and format but no fixed pixel dimensions. (The older '10-50 KB' spec is outdated.)",
    source: { url: "https://afcat.cdac.in", label: "AFCAT (afcat.cdac.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },

  // ---------------------------------------------------------------------------
  // State PSCs — confirmed against official portal/OTR/notification PDFs.
  // ---------------------------------------------------------------------------
  rpsc: {
    id: "rpsc",
    name: "RPSC (Rajasthan PSC)",
    photoLimitKb: 100,
    photoMinKb: 50,
    sigLimitKb: 50,
    sigMinKb: 10,
    photoWidthPx: 350,
    photoHeightPx: 450,
    sigWidthPx: 420,
    sigHeightPx: 120,
    photoAspectRatio: 3.5 / 4.5,
    sigAspectRatio: 420 / 120,
    description: "Rajasthan PSC (via SSO Rajasthan recruitment portal). Photo 50-100 KB (3.5x4.5 cm, 240x320 to 480x640 px); signature 10-50 KB (7x2 cm box, 280x80 to 560x160 px); JPG/JPEG.",
    source: { url: "https://rpsc.rajasthan.gov.in", label: "RPSC (rpsc.rajasthan.gov.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  tnpsc: {
    id: "tnpsc",
    name: "TNPSC (Tamil Nadu PSC)",
    photoLimitKb: 50,
    sigLimitKb: 20,
    photoWidthPx: 350,
    photoHeightPx: 400,
    sigWidthPx: 250,
    sigHeightPx: 180,
    description: "Tamil Nadu PSC. Photo under 50 KB (300-400 x 250-400 px); signature under 20 KB (200-300 x 150-250 px); JPG/JPEG. No minimum file size is specified.",
    source: { url: "https://tnpsc.gov.in", label: "TNPSC (tnpsc.gov.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  kpsc: {
    id: "kpsc",
    name: "KPSC (Karnataka PSC)",
    photoLimitKb: 200,
    sigLimitKb: 50,
    photoWidthPx: 150,
    photoHeightPx: 150,
    sigWidthPx: 150,
    sigHeightPx: 150,
    description: "Karnataka PSC (online application portal). Photo up to 200 KB (100x100 to 150x150 px); signature up to 50 KB (50x50 to 150x150 px); JPG/JPEG/PNG. Specific exam notifications may impose tighter limits.",
    source: { url: "https://kpsc.kar.nic.in", label: "KPSC (kpsc.kar.nic.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  appsc: {
    id: "appsc",
    name: "APPSC (Andhra Pradesh PSC)",
    photoLimitKb: 50,
    sigLimitKb: 30,
    description: "Andhra Pradesh PSC (OTPR registration). Photo about 50 KB (3.5x4.5 cm, with name + date printed on it); signature about 30 KB (3.5x1.5 cm), uploaded separately; JPG. The official manual gives cm + KB but no pixel dimensions.",
    source: { url: "https://psc.ap.gov.in", label: "APPSC (psc.ap.gov.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  tgpsc: {
    id: "tgpsc",
    name: "TGPSC / TSPSC (Telangana PSC)",
    photoLimitKb: 50,
    photoMinKb: 4,
    sigLimitKb: 30,
    sigMinKb: 1,
    description: "Telangana PSC (One Time Registration). Photo 4-50 KB (3.5x4.5 cm); signature 1-30 KB (3.5x1.5 cm), uploaded separately; JPG/JPEG/PNG. The official OTR manual gives cm + KB but no pixel dimensions.",
    source: { url: "https://tgpsc.gov.in", label: "TGPSC (tgpsc.gov.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  wbpsc: {
    id: "wbpsc",
    name: "WBPSC (West Bengal PSC)",
    photoLimitKb: 50,
    sigLimitKb: 50,
    description: "West Bengal PSC. Photo up to 50 KB (3.5x4.5 cm); signature up to 50 KB (3.5x1.5 cm); JPG/JPEG. Some WBPSC notifications cap the photo at 100 KB instead — confirm the current notification.",
    source: { url: "https://wbpsc.gov.in", label: "WBPSC (wbpsc.gov.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  gpsc: {
    id: "gpsc",
    name: "GPSC (Gujarat PSC)",
    photoLimitKb: 15,
    sigLimitKb: 15,
    description: "Gujarat PSC (via OJAS). Photo up to 15 KB (5 cm x 3.6 cm); signature up to 15 KB (signed in blue/black ink); JPG. The official guideline gives cm + a 15 KB cap but no pixel dimensions.",
    source: { url: "https://gpsc.gujarat.gov.in", label: "GPSC (gpsc.gujarat.gov.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  hpsc: {
    id: "hpsc",
    name: "HPSC (Haryana PSC)",
    photoLimitKb: 500,
    sigLimitKb: 500,
    photoWidthPx: 150,
    photoHeightPx: 190,
    sigWidthPx: 150,
    sigHeightPx: 60,
    description: "Haryana PSC (online registration). Photo up to 500 KB (132x170 to 160x204 px); signature up to 500 KB (132x57 to 160x68 px); JPG/JPEG/PNG.",
    source: { url: "https://hpsc.gov.in", label: "HPSC (hpsc.gov.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },

  // ---------------------------------------------------------------------------
  // Banking & insurance (IBPS-standard) — confirmed against official notices.
  // ---------------------------------------------------------------------------
  nabard: {
    id: "nabard",
    name: "NABARD (Grade A / B)",
    photoLimitKb: 50,
    photoMinKb: 20,
    sigLimitKb: 20,
    sigMinKb: 10,
    photoWidthPx: 200,
    photoHeightPx: 230,
    sigWidthPx: 140,
    sigHeightPx: 60,
    photoAspectRatio: 20 / 23,
    sigAspectRatio: 14 / 6,
    description: "NABARD recruitment (IBPS-administered). Photo 20-50 KB (200x230 px); signature 10-20 KB (140x60 px); JPG/JPEG, min 200 DPI.",
    source: { url: "https://nabard.org", label: "NABARD (nabard.org)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  lic: {
    id: "lic",
    name: "LIC (AAO / ADO)",
    photoLimitKb: 50,
    photoMinKb: 20,
    sigLimitKb: 20,
    sigMinKb: 10,
    photoWidthPx: 200,
    photoHeightPx: 230,
    sigWidthPx: 140,
    sigHeightPx: 60,
    photoAspectRatio: 20 / 23,
    sigAspectRatio: 14 / 6,
    description: "LIC recruitment (AAO / ADO). Photo 20-50 KB (200x230 px); signature 10-20 KB (140x60 px); JPG/JPEG.",
    source: { url: "https://licindia.in", label: "LIC India (licindia.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  niacl: {
    id: "niacl",
    name: "NIACL (AO / Assistant)",
    photoLimitKb: 50,
    photoMinKb: 20,
    sigLimitKb: 20,
    sigMinKb: 10,
    photoWidthPx: 200,
    photoHeightPx: 230,
    sigWidthPx: 140,
    sigHeightPx: 60,
    photoAspectRatio: 20 / 23,
    sigAspectRatio: 14 / 6,
    description: "New India Assurance (NIACL AO / Assistant). Photo 20-50 KB (200x230 px); signature 10-20 KB (140x60 px); JPG/JPEG.",
    source: { url: "https://www.newindia.co.in", label: "NIACL (newindia.co.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
  irdai: {
    id: "irdai",
    name: "IRDAI (Assistant Manager)",
    photoLimitKb: 50,
    photoMinKb: 20,
    sigLimitKb: 20,
    sigMinKb: 10,
    photoWidthPx: 200,
    photoHeightPx: 230,
    sigWidthPx: 140,
    sigHeightPx: 60,
    photoAspectRatio: 20 / 23,
    sigAspectRatio: 14 / 6,
    description: "IRDAI recruitment (Assistant Manager). Photo 20-50 KB (200x230 px); signature 10-20 KB (140x60 px); JPG/JPEG, min 200 DPI.",
    source: { url: "https://irdai.gov.in", label: "IRDAI (irdai.gov.in)" },
    verification: "official",
    verifiedOn: "2026-06-10",
  },
};

export const PORTAL_KEYS = Object.keys(PORTAL_PRESETS) as Array<keyof typeof PORTAL_PRESETS>;
